# Variables
# ---------
@baseUrl = http://{{$dotenv APP_ADDR}}:{{$dotenv APP_PORT}}/api/v1
@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJjcmVhdGVkQXQiOiIyMDIxLTAzLTA5VDIwOjA1OjM1LjU2NFoiLCJleHAiOjE2NTA3NzkwMTcsImZpcnN0bmFtZSI6IlRvdG8gMiIsImlhdCI6MTY0OTkxNTAxNywiaWQiOiJjYjEzY2MyOS0xM2JiLTRiODQtYmYzMC0xN2RhMDBlYzc0MDAiLCJsYXN0bmFtZSI6IlRlc3QiLCJuYmYiOjE2NDk5MTUwMTcsInVzZXJuYW1lIjoidGVzdEBnbWFpbC5jb20ifQ.lhDMR8JQHRYai3xmjB_9H3jwqpfPrw2xU3tYmofv_GC_T15XDvL67CUOKvYOBPvwCc_9X4LOO3nHyTlJPzwytA


# Users
# -----
@userId = cb13cc29-13bb-4b84-bf30-17da00ec7400
@userIdToDelete = 2ae3ae27-2eb8-4cd5-b2f8-9ef6ae3d5b9b

# Login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "test@gmail.com",
    "password": "00000000"
}
###

# Register
POST {{baseUrl}}/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "test44@gmail.com",
    "password": "00000000",
    "lastname": "Test",
    "firstname": "Toto"
}
###

# Users list
GET {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{token}}
###

# User information
GET {{baseUrl}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}
###

# Update user
PUT {{baseUrl}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "test@gmail.com",
    "password": "00000000",
    "lastname": "Test",
    "firstname": "Toto 2"
}
###

# Delete user
DELETE {{baseUrl}}/users/{{userIdToDelete}}
Content-Type: application/json
Authorization: Bearer {{token}}
###
