package main

import (
	"log"
	"time"

	server "github.com/fabienbellanger/fiber-boilerplate"
	"github.com/fabienbellanger/fiber-boilerplate/db"
	"github.com/fabienbellanger/fiber-boilerplate/logger"
	"github.com/fabienbellanger/fiber-boilerplate/ws"
	"github.com/spf13/viper"

	// docs are generated by Swag CLI, you have to import them.
	_ "github.com/fabienbellanger/fiber-boilerplate/docs"
)

// @title Fiber Boilerplate
// @version 1.0
// @description This is a boilerplate for Fiber
// @contact.name API Support
// @contact.email valentil@gmail.com
// @license.name Apache 2.0
// @securityDefinitions.basic BearerAuth
// @tokenUrl http://localhost:3000/api/login
// @host localhost:3000
// @BasePath /api
func main() {
	// Configuration initialization
	// ----------------------------
	if err := initConfig(); err != nil {
		log.Fatalln(err)
	}

	// Logger initialization
	// ---------------------
	logger, err := logger.Init()
	if err != nil {
		log.Fatalln(err)
	}
	defer logger.Sync()

	// Database connection
	// -------------------
	db, err := db.New(&db.DatabaseConfig{
		Driver:          viper.GetString("DB_DRIVER"),
		Host:            viper.GetString("DB_HOST"),
		Username:        viper.GetString("DB_USERNAME"),
		Password:        viper.GetString("DB_PASSWORD"),
		Port:            viper.GetInt("DB_PORT"),
		Database:        viper.GetString("DB_DATABASE"),
		MaxIdleConns:    viper.GetInt("DB_MAX_IDLE_CONNS"),
		MaxOpenConns:    viper.GetInt("DB_MAX_OPEN_CONNS"),
		ConnMaxLifetime: viper.GetDuration("DB_CONN_MAX_LIFETIME") * time.Hour,
	})
	if err != nil {
		log.Fatalln(err)
	}

	// Database migrations
	// -------------------
	if viper.GetBool("DB_USE_AUTOMIGRATIONS") {
		db.MakeMigrations()
	}

	// Hub for websockets broadcast
	// ----------------------------
	hub := ws.NewHub()
	go hub.Run()

	// Start server
	// ------------
	server.Run(db, hub, logger)
}

// initConfig initializes configuration from config file.
func initConfig() error {
	viper.SetConfigFile(".env")
	return viper.ReadInConfig()
}
